language: node_js

node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'

services:
  - mongodb

sudo: false

env:
  - NODE_ENV=test

git:
  submodules: false

before_script:
  - npm install

script:
  - npm test

after_success:
  - npm run report-coveralls
  - npm run report-codecov
